// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbaaszGVTnzn5HySzfbxTeSiWpoXCrTFw',
    appId: '1:296671498266:web:89afd0f2822538b63741a3',
    messagingSenderId: '296671498266',
    projectId: 'crm-app-flutter-a1740',
    authDomain: 'crm-app-flutter-a1740.firebaseapp.com',
    storageBucket: 'crm-app-flutter-a1740.appspot.com',
    measurementId: 'G-VBVLB32GEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1hV5i3F65bt1zJD90ReALAGBUhxs6xUc',
    appId: '1:296671498266:android:8ca35bdf1d2306a33741a3',
    messagingSenderId: '296671498266',
    projectId: 'crm-app-flutter-a1740',
    storageBucket: 'crm-app-flutter-a1740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLHzFAQ1b6kpiYpUSaJIjz7smyN0Ht-Fg',
    appId: '1:296671498266:ios:0b3f9d0d4482313f3741a3',
    messagingSenderId: '296671498266',
    projectId: 'crm-app-flutter-a1740',
    storageBucket: 'crm-app-flutter-a1740.appspot.com',
    iosBundleId: 'com.mr_peru.crmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLHzFAQ1b6kpiYpUSaJIjz7smyN0Ht-Fg',
    appId: '1:296671498266:ios:0b3f9d0d4482313f3741a3',
    messagingSenderId: '296671498266',
    projectId: 'crm-app-flutter-a1740',
    storageBucket: 'crm-app-flutter-a1740.appspot.com',
    iosBundleId: 'com.mr_peru.crmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbaaszGVTnzn5HySzfbxTeSiWpoXCrTFw',
    appId: '1:296671498266:web:12a6f62a7650161a3741a3',
    messagingSenderId: '296671498266',
    projectId: 'crm-app-flutter-a1740',
    authDomain: 'crm-app-flutter-a1740.firebaseapp.com',
    storageBucket: 'crm-app-flutter-a1740.appspot.com',
    measurementId: 'G-ZP8H246G6E',
  );
}
